applications/Departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='departamento_app'
urlpatterns = [
   path(
      'nuevo-departamento/', 
      views.NuevoDepartementoView.as_view(), 
      name='nuevo_depto'),
      path(
      'departamentos/', 
      views.DepartamentoListView.as_view(), 
      name='departamentos'),
      

]

applications/Empleado/urls.py
from django.contrib import admin
from django.urls import path

from . import views
""" Usamos la siguiente linea para darle un nombre a todo el congunto de urls 
    app_name"""

app_name = "empleado_app"

urlpatterns = [
    path('', views.InicioHome.as_view(), name='inicio'),
    path(
        'listar-empleados/', 
        views.EmpleadosListView.as_view(),
        name='todos-empleados'
    ),
    path(
        'listar-empleados-area/<shorname>/', 
        views.ListByAreaListView.as_view(),
        name='empleados_area'
        ),
    path(
        'listar-empleados-job/<shorname>/', 
        views.ListByJobListView.as_view(),
        name='empleados_job'
    ),
    path(
        'buscar_empleado/', 
        views.ListEmpleadosWKListView.as_view()
    ),
    path(
        'listar-habilidades-empleado/<id>/', 
        views.HabilidadesListView.as_view()
    ),
    path(
        'detalle_empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='detalle_emp'
    ),
    path(
        'add_empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='agregar_empleado'),
    # name = correcto es una etiqueta para llamar a esta url """
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path(
        'update-empleado/<pk>/', 
        views.EmpleadoUpdateView.as_view(), 
        name='modificar_empleado'
    ),
    path(
         'delete-empleado/<pk>/', 
         views.EmpleadoDeleteView.as_view(), 
         name='eliminar_empleado'
        ),
    path(
         'admin-empleados/', 
         views.EmpleadosEditarListView.as_view(), 
         name='editar_empleados'
        ),
]

project01/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #Urls de apps
    re_path('', include('applications.Departamento.urls')),
    re_path('', include('applications.Empleado.urls')),
    re_path('', include('applications.home.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li><a href="{% url 'empleado_app:todos-empleados' %}">Listar</a></li>
        <li><a href="{% url 'departamento_app:departamentos' %}">Departamento</a></li>
        <li><a href="#">Administrar</a>
          <ul class="menu vertical">
            <li><a href="{% url 'empleado_app:editar_empleados' %}">Editar empleados</a></li>
            <li><a href="{% url 'departamento_app:nuevo_depto' %}">Nuevo departamento </a></li>
          </ul>
      </li>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar"></li>
        <li><a href="{% url 'empleado_app:agregar_empleado' %} " class="button">Registrar nuevo</a></li>
      </ul>
    </div>
  </div>