applications/Departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='departamento_app'
urlpatterns = [
   path(
      'nuevo-departamento/', 
      views.NuevoDepartementoView.as_view(), 
      name='nuevo_depto'),
      path(
      'departamentos/', 
      views.DepartamentoListView.as_view(), 
      name='departamentos'),
      

]

applications/Empleado/urls.py
from django.contrib import admin
from django.urls import path

from . import views
""" Usamos la siguiente linea para darle un nombre a todo el congunto de urls 
    app_name"""

app_name = "empleado_app"

urlpatterns = [
    path('', views.InicioHome.as_view(), name='inicio'),
    path(
        'listar-empleados/', 
        views.EmpleadosListView.as_view(),
        name='todos-empleados'
    ),
    path(
        'listar-empleados-area/<shorname>/', 
        views.ListByAreaListView.as_view(),
        name='empleados_area'
        ),
    path(
        'listar-empleados-job/<shorname>/', 
        views.ListByJobListView.as_view(),
        name='empleados_job'
    ),
    path(
        'buscar_empleado/', 
        views.ListEmpleadosWKListView.as_view()
    ),
    path(
        'listar-habilidades-empleado/<id>/', 
        views.HabilidadesListView.as_view()
    ),
    path(
        'detalle_empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='detalle_emp'
    ),
    path(
        'add_empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='agregar_empleado'),
    # name = correcto es una etiqueta para llamar a esta url """
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path(
        'update-empleado/<pk>/', 
        views.EmpleadoUpdateView.as_view(), 
        name='modificar_empleado'
    ),
    path(
         'delete-empleado/<pk>/', 
         views.EmpleadoDeleteView.as_view(), 
         name='eliminar_empleado'
        ),
    path(
         'admin-empleados/', 
         views.EmpleadosEditarListView.as_view(), 
         name='editar_empleados'
        ),
]

project01/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #Urls de apps
    re_path('', include('applications.Departamento.urls')),
    re_path('', include('applications.Empleado.urls')),
    re_path('', include('applications.home.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/Departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    shor_name = models.CharField('Nombre corto', max_length=50)
    active = models.BooleanField('Activo',default=True)

    """
    para mandar una imagen en blanco necesitamos:
    null=true
    para dejar un campo opcional
    blanck =true
    Para crear un campo unico
    unique=true
    para que nadie pueda acceder desde el administradoor
    editable=false
    """

    class Meta:
        verbose_name='Mi departamento'
        verbose_name_plural='Areas de la empresa'
        ordering=['name'] #Orden inverso [-'name'], soporta muchos atributos ya que es una lista
        unique_together=('name','shor_name')#impide una combinacion de valores

    def __str__(self):
        return "{} - {}".format(self.name, self.active)

applications/Departamento/forms.py
from django import forms

class NuevoDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shortname = forms.CharField(max_length=20)

applications/Departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView
from .forms import NuevoDepartamentoForm

from applications.Empleado.models import Empleado
from .models import Departamento
#la vista generica que utilizamos para formularios
#que no estan vinculados a un solo modelo se llama
#FormView
class NuevoDepartementoView(FormView):
    """NuevoDepartementoView definition."""
    template_name = 'Departamento/nuevo_departamento.html'
    form_class = NuevoDepartamentoForm
    success_url = '.'

    #esta funcion es obligatoria
    def form_valid (self, form):

        dep = Departamento(
            name= form.cleaned_data['departamento'],
            shor_name= form.cleaned_data['shortname'],

        )
        dep.save()

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellido']
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job='1',
            departamento_id=dep
        )
        return super(NuevoDepartementoView, self).form_valid(form)

class DepartamentoListView(ListView):
    model = Departamento
    template_name = "Departamento/todos_departamentos.html"
    paginate_by = 5

templates/Departamento/nuevo_departamento.html
{% extends 'base.html' %}
    {% block title %}
     Agregar nuevo departamento
    {% endblock title %}

    {% block contenent %}
        <div class="grid-container">
            <div class="grid-x">
                <h1 class="cell centro">Registar nuevo departamento</h1>
                <div class="cell">
                    <form  class="grid-x grid-margin-x" method="post"> {% csrf_token %}
                        <h4 class="cell centro">Datos Empleado</h4>
                        <div class="cell large-6 medium-6 small-12">
                            <label>Nombre
                                {{form.nombre}}
                            </label>
                        </div>
                        <div class="cell large-6 medium-6 small-12">
                            <label>Apellido
                                {{form.apellido}}
                            </label>
                            <br>
                        </div>
                        <h4 class="centro cell large-12">Datos Departamento</h4>
                        <div class="cell large-6 medium-6 small-12">
                            <label>Nombre del departamento
                                {{form.departamento}}
                            </label>
                        </div>
                        <div class="cell large-6 medium-6 small-12">
                            <label>Nombre corto
                                {{form.shortname}}
                            </label>
                        </div>
                        <div class="cell">
                            <button class="button expanded" type="submit">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    {% endblock contenent %}

templates/Departamento/todos_departamentos.html
{% extends 'base.html' %}
{% block title %}
    Departamentos
{% endblock title %}

{% block contenent %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell large-12">Departamentos de la empresa</h1>
            <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="350">&Aacute;rea</th>
                    <th width="200">Abreviatura</th>
                    <th width="200" style="text-align: center">Acci&oacute;n</th>
                  </tr>
                </thead>
                <tbody>
                    
                    {% for dep in object_list %}
                  <tr>
                    <td>{{dep.name}}</td>
                    <td>{{dep.shor_name}}</td>
                    <td  style="text-align: center">
                        <a class="button success" href="{% url 'empleado_app:empleados_area' dep.shor_name %}">
                            Ver empleados del &aacute;rea</a>
                    </td>
        
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
              <div class="cell">
                {% if is_paginated %}      
                  <nav aria-label="Pagination">
                       <ul class="pagination">
                          {% if page_obj.has_previous %}
                               <li class="pagination-previous">
                                   <a href="?page={{page_obj.previous_page_number}}">Anterior</a>  
                               </li>
                           {% endif %}
                           {% for pagina in paginator.page_range %}
                               
                               {% ifequal pagina  page_obj.number  %} 
                                   <li class="current">
                                       <span class="show-for-sr">You're on page</span> {{pagina}}
                                   </li>
                               {% else %}
                                   <li><a href="?page={{pagina}}" >{{pagina}}</a></li>             
                               {% endifequal %}
                           {% endfor %}
                           {% if page_obj.has_next %}
                           <li class="pagination-next">
                               <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                           </li>
                           {% endif %}
                       </ul>
                   </nav>
                            
               {% endif %}
           </div>
        </div>
`   </div>
{% endblock contenent %}

    