applications/Empleado/urls.py
from django.contrib import admin
from django.urls import path

from . import views
""" Usamos la siguiente linea para darle un nombre a todo el congunto de urls 
    app_name"""

app_name = "empleado_app"

urlpatterns = [
    path('', views.InicioHome.as_view(), name='inicio'),
    path(
        'listar-empleados/', 
        views.EmpleadosListView.as_view(),
        name='todos-empleados'
    ),
    path(
        'listar-empleados-area/<shorname>/', 
        views.ListByAreaListView.as_view(),
        name='empleados_area'
        ),
    path(
        'listar-empleados-job/<shorname>/', 
        views.ListByJobListView.as_view(),
        name='empleados_job'
    ),
    path(
        'buscar_empleado/', 
        views.ListEmpleadosWKListView.as_view()
    ),
    path(
        'listar-habilidades-empleado/<id>/', 
        views.HabilidadesListView.as_view()
    ),
    path(
        'detalle_empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='detalle_emp'
    ),
    path(
        'add_empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='agregar_empleado'),
    # name = correcto es una etiqueta para llamar a esta url """
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path(
        'update-empleado/<pk>/', 
        views.EmpleadoUpdateView.as_view(), 
        name='modificar_empleado'
    ),
    path(
         'delete-empleado/<pk>/', 
         views.EmpleadoDeleteView.as_view(), 
         name='eliminar_empleado'
        ),
    path(
         'admin-empleados/', 
         views.EmpleadosEditarListView.as_view(), 
         name='editar_empleados'
        ),
]

project01/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #Urls de apps
    re_path('', include('applications.Departamento.urls')),
    re_path('', include('applications.Empleado.urls')),
    re_path('', include('applications.home.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/Empleado/models.py
from django.db import models
from  applications.Departamento.models import Departamento

#ckeditor
from ckeditor.fields import RichTextField


# Create your models here.
class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name='Habilidad'
        verbose_name_plural='Habilidades de empleado'
        ordering=['habilidad'] #Orden inverso [-'name'], soporta muchos atributos ya que es una lista
        #unique_together=('first_name','last_name')
    def __str__(self):
        return "{}".format(self.habilidad)

class Empleado(models.Model):
    JOB_CHOICES= (
        ('0', 'Titular'),
        ('1', 'Rotar en plantilla'),
        ('2', 'Esporadico'),
        ('3', 'Otro'),
    )
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellido', max_length=60)
    full_nam = models.CharField(
            'Nombre completo', 
            max_length=120,
            blank=True)
    job = models.CharField('Trabajo', max_length=1,choices=JOB_CHOICES)
    #uno a muchos
    departamento_id = models.ForeignKey( Departamento, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='empleado', blank=True, null=True)
    
    #muchos a muchos
    habilidades = models.ManyToManyField(Habilidades)

    #ckeditor
    hoja_vida = RichTextField()

    class Meta:
        verbose_name='Empleado'
        verbose_name_plural='Empleados'
        ordering=['id'] #Orden inverso [-'name'], soporta muchos atributos ya que es una lista
        unique_together=('first_name','last_name')#impide una combinacion de valores
    
    def __str__(self):
        return "{} - {}".format(self.first_name, self.last_name)

applications/Empleado/forms.py
from django import forms
from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    class Meta:
        model = Empleado
        fields = (
            'first_name', 
            'last_name', 
            'job', 
            'departamento_id', 
            'habilidades',
            'image',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple
        }

applications/Empleado/views.py
from django.shortcuts import render
#paqute para enviar a una url
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView, 
    DeleteView
)
from .forms import EmpleadoForm

#clase para el home
class InicioHome(TemplateView):
    template_name = "index.html"


#list view  requiere un qery set o medelo para trabajar
from .models import Empleado

#vista todos los empleadors

class EmpleadosListView(ListView):
   
    #paginacion
    template_name = "Empleado/list_all.html"
    paginate_by = 4
    ordering = 'first_name' 

    def get_queryset(self):
        #interceptar datos enviados por formulario
        palabra_clave = self.request.GET.get("kword", "")
        #__icontains busca palabras que coincidan
        lista =  Empleado.objects.filter(
            full_nam__icontains =  palabra_clave
        )
       
        return lista


class EmpleadosEditarListView(ListView):
   
    #paginacion
    template_name = "Empleado/lista_editar.html"
    paginate_by = 10
    ordering = 'first_name'
    context_object_name  =  'empleados'
    model = Empleado


class ListByAreaListView(ListView):
    """  queryset = Empleado.objects.filter(
        departamento_id__name='Area contable'
        ) """
    template_name = "Empleado/list_area.html"
    paginate_by = 4
    
     
        #sobreescribimos una funcion de las vistas en listviewtree 
    def get_queryset(self):
        #recogemos un parametro del url
        area = self.kwargs['shorname']
        
        lista =  Empleado.objects.filter(
        departamento_id__shor_name=area
        )
        #para esta funcion siempre debemos retornar una lista
        return lista



class ListByJobListView(ListView):
    template_name = "Empleado/list_job.html"
    #context_object_name = "empleados"
        #sobreescribimos una funcion de las vistas en listviewtree 
    def get_queryset(self):
        #recogemos un parametro del url
        job = self.kwargs['shorname']        
        lista =  Empleado.objects.filter(
        job=job
        )
        print(lista)
        #para esta funcion siempre debemos retornar una lista
        return lista


class ListEmpleadosWKListView(ListView):
    model = Empleado
    template_name = "empleado/by_kword.html"
    #variable para trabajarla en el html (no necesaria)
    context_object_name='empleados'
    def get_queryset(self):
        #interceptar datos enviados por formulario
        palabra_clave = self.request.GET.get("kword", "")
        lista =  Empleado.objects.filter(
        first_name=palabra_clave
        )
        return lista


class HabilidadesListView(ListView):
    template_name = "Empleado/habilidades.html"
    context_object_name = 'habilidades'
    #model = Habilidades

    def get_queryset(self):
        emp = self.kwargs['id']
        
        #metodo get recupera un unico  registro
        empleado = Empleado.objects.get(id=emp)       
        return empleado.habilidades.all()
 
#Esta clase nos ayuda para mostrar mas detalles

class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "Empleado/detalle_empleado.html"

    """Sobre escribiendo un metodo para enviar una variable
    al front """
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["titulo"] = 'Empleado del mes'
        return context

#vista basica
""" Usaremos esta clase (vista basica) con el unico proposito 
de que despues de guardar un emleado nos mande a este template """
class SuccessView(TemplateView):
    template_name = "Empleado/success.html"


# Vista generica para Registrar algo en el modelo de la base de datos 
class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "Empleado/add.html"
    #Aqui llamamos a todos los campos del modelo
    #fields = ('__all__')
    """ Sin no queremos agregar todos los campos del modelo usamos:"""
    #fields = ['first_name', 'last_name', 'job', 'departamento_id', 'habilidades','image'] 
    #Aqui indicamos a donde quremos que nos lleve la pagina al completar el formulario
    #en este ejemplo solo recargaremos la pagina
    #success_url = '.'
    #Asi indicamos el envio a otra pagina
    #success_url = '/success'
    #asi usando el paquete de la segunda linea de este archivo
    form_class = EmpleadoForm
    success_url = reverse_lazy('empleado_app:todos-empleados')

    #funcion para crear el full name
    def form_valid(self, form):
        #commit = False ayuda a no generar un doble guardado
        empleado = form.save(commit = False)
        empleado.full_nam = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "Empleado/update.html"

    form_class = EmpleadoForm
    """ fields = [
        'first_name', 
        'last_name', 
        'job', 
        'departamento_id', 
        'habilidades'
    ] """
    success_url = reverse_lazy('empleado_app:editar_empleados')

    #este metodo podemos usarlo en el create view tambien
    # proceso para guardar datos antes de ser validados
    #def post(self, request, *args, **kwargs):
    #    print(request.POST)
    #    return super().post(request, *args, **kwargs) 


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "Empleado/delete.html"
    success_url = reverse_lazy('empleado_app:editar_empleados')

templates/Empleado/add.html
{% extends 'base.html' %}


{% block title %}
    Agregar Empleado
{% endblock title %}
    

{% block contenent %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Registrar un empleado</h1>
            <div class="cell">
                <!-- creando un formulario, lo necesitamos por el boton post -->
               <form class="grid-x grid-margin-x" action="" method="post" enctype="multipart/form-data"> {% csrf_token %}
                   <!-- la variable form tiene muchos metodos a los que podemos acceder desde
                       aqui por ejemplo el metodo  as_p orenada en etiquetas de parrafo
                       recordemos que este html viene de un createview 
                       {{ form.as_p }}-->
                    <div class="cell large-6 medium-6 small-12">
                        <label>Nombre
                            {{form.first_name}}
                        </label>
                    </div>
                    <div class="cell large-6 medium-6 small-12">
                        <label>Apellido
                            {{form.last_name}}
                        </label>
                    </div>
                    <div class="cell large-6 medium-6 small-12">
                        <label>Trabajo
                            {{form.job}}
                        </label>
                    </div>
                    <div class="cell large-6 medium-6 small-12">
                        <label>Departamento
                            {{form.departamento_id}}
                        </label>
                    </div>
                    <div class="cell large-12">
                        <label>Departamento
                            {{form.habilidades}}
                        </label>
                    </div>
                    <div class="cell large-12">
                        <label>Foto
                            {{form.image}}
                        </label>
                    </div>
                    <div class="cell">
                        <button class="success button" type="submit">Agregar</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
{% endblock contenent %}    

templates/Empleado/by_kword.html
<h1>Buscar empleado</h1>
<form  method="get">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese el nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Resultados</h3>

{% if empleados %}
    {% for e in empleados %}
        <li>{{e}}</li>
    {% endfor %}
{% else %}
    <li>Sin resultados</li>
{% endif %}
    

templates/Empleado/delete.html
{% extends 'base.html' %}


{% block title %}
    Eliminar empleado {{object.full_nam}}
{% endblock title %}
    

{% block contenent %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Eliminar  {{ object.full_nam }}</h1>
            <div class="cell">
                <form action="" method="post">{% csrf_token %}
                    <div class="callout alert">
                        <h5>Confirme que desea eliminar {{ object.full_nam }}</h5>
                    <button class="button alert" type="submit">Confirmar</button>
                </form>
            </div>
        </div>




    </div>
{% endblock contenent   %}
    
    
<h1>Eliminar</h1>
<form action="" method="post">{% csrf_token %}
    <p>Confirme que desea eliminar</p>
    <button type="submit">Confirmar</button>
</form>

templates/Empleado/detalle_empleado.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
    {{object.first_name}}
{% endblock title %}

{% block contenent %}
    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center">
            <div class="cell large-4 card" style="width: 300px; margin-top: 10px;">
                <div class="card-divider centro">
                  <h1>{{empleado.get_job_display}}</h1>
                </div>
                
                {% if empleado.image %}
                    <img src="{{empleado.image.url}}">
                {% else %}
                    <img src="{% static 'img/siete.jpg' %}">
                {% endif %}
                    
                <div class="card-section">
                  <h4>{{empleado.full_name}}</h4>
                  <p>{{empleado.first_name}}</p>
                  <p>Posici&oacute;n: <b> {{empleado.departamento_id.shor_name}}</b></p>
                  <p> <span class="label">Habilidades: </span></p>
                  <ul class="vertuical menu">
                      {% for h in empleado.habilidades.all %}
                        <li>{{h.habilidad}}</li>
                      {% endfor %}      
                  </ul>
                </div>
              </div>

            
            <!-- recupera todo los valores del detai view
            podemos usar object o el nombre de nuestro modelo -->
           
        </div>
    </div>
{%endblock%}

templates/Empleado/habilidades.html
<h1>Habilidades de empleado</h1>
<ul>
    
    {% for habilidad in habilidades %}
        <li>{{habilidad}}</li>
    {% endfor %}
        
</ul>

templates/Empleado/list_all.html
{% extends 'base.html' %}

{% block title %}
    Buscar Empleados
{% endblock title %}
    

{% block contenent %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell large-12">Lista de empleados</h1>
            <form class="cell large-12 grid-x grid-margin-x" method="GET">{% csrf_token %}
                <div class="cell large-7 ">
                    <input type="text" id="kword" name="kword" placeholder="Buscar empleado">
                </div>
                <div class="cell large-2">
                    <button type="submit" class="success button">Buscar</button>
                </div>
            </form>
            <div class="cell">
                <table>
                    <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th width="200">Nombre</th>
                        <th width="150">Apellido</th>
                        <th width="150">Departamento</th>
                        <th width="150">Acci&oacute;n</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for empleado in object_list %}
                        <tr>
                            <td>{{ empleado.id }}</td>
                            <td>{{ empleado.first_name }}</td>
                            <td>{{ empleado.last_name }}</td>
                            <td>{{ empleado.departamento_id }}</td>
                            <td> <a class="button warning" href="{% url 'empleado_app:detalle_emp' empleado.id %}">Ver</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>     
            </div>
            
            <!-- Si en nuestras vistas
            no enviamos el parametro context_object_name
            usaremos object_list  -->
        
            <div class="cell">
                 {% if is_paginated %}      
                   <nav aria-label="Pagination">
                        <ul class="pagination">
                           {% if page_obj.has_previous %}
                                <li class="pagination-previous">
                                    <a href="?page={{page_obj.previous_page_number}}">Anterior</a>  
                                </li>
                            {% endif %}
                            {% for pagina in paginator.page_range %}
                                
                                {% ifequal pagina  page_obj.number  %} 
                                    <li class="current">
                                        <span class="show-for-sr">You're on page</span> {{pagina}}
                                    </li>
                                {% else %}
                                    <li><a href="?page={{pagina}}" >{{pagina}}</a></li>             
                                {% endifequal %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                             
                {% endif %}
            </div>
        </div>
    </div>
{% endblock contenent %}

templates/Empleado/list_area.html
{% extends 'base.html' %}


{% block title %}
   Empleados del area {{object_list.departamento_id}}
{% endblock title %}
   
{% block contenent %}
<p>{{text}}</p>
<div class="grid-container">
   <div class="grid-x">
      <h1 class="cell large-12">Empleados del area</h1>

      {% if not object_list %}
         <h5 class="cell large-12">El area no tiene ningun empleado</h5>
      {% else %}
      <div class="cell">
         <table>
             <thead>
             <tr>
                 <th width="200">ID</th>
                 <th width="200">Nombre</th>
                 <th width="150">Apellido</th>
                 <th width="150">Departamento</th>
                 <th width="150">Acci&oacute;n</th>
             </tr>
             </thead>
             <tbody>
                 {% for empleado in object_list %}
                 <tr>
                     <td>{{ empleado.id }}</td>
                     <td>{{ empleado.first_name }}</td>
                     <td>{{ empleado.last_name }}</td>
                     <td>{{ empleado.departamento_id }}</td>
                     <td> <a class="button warning" href="{% url 'empleado_app:detalle_emp' empleado.id %}">Ver</a></td>
                 </tr>
                 {% endfor %}
             </tbody>
         </table>     
     </div>
     
     <!-- Si en nuestras vistas
     no enviamos el parametro context_object_name
     usaremos object_list  -->
 
     <div class="cell">
          {% if is_paginated %}      
            <nav aria-label="Pagination">
                 <ul class="pagination">
                    {% if page_obj.has_previous %}
                         <li class="pagination-previous">
                             <a href="?page={{page_obj.previous_page_number}}">Anterior</a>  
                         </li>
                     {% endif %}
                     {% for pagina in paginator.page_range %}
                         
                         {% ifequal pagina  page_obj.number  %} 
                             <li class="current">
                                 <span class="show-for-sr">You're on page</span> {{pagina}}
                             </li>
                         {% else %}
                             <li><a href="?page={{pagina}}" >{{pagina}}</a></li>             
                         {% endifequal %}
                     {% endfor %}
                     {% if page_obj.has_next %}
                     <li class="pagination-next">
                         <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                     </li>
                     {% endif %}
                 </ul>
             </nav>
                      
         {% endif %}
     </div>
         {% endif %}
   </div>
</div>

{% endblock contenent %}

templates/Empleado/list_job.html
{% extends 'base.html' %}
{% block title %}
   Empleados del area
{% endblock title %}

{% block contenent %}
   <h1>Empleados del area</h1>
   <p>{{object_list}}</p>
   {% if object_list %}
      {%for job in object_list%}
         <li> {{job}}</li>
      {%endfor%}
   {% else %}
      <h3>El &aacute;rea no cuenta con empleados registrados</h3>
   {% endif %}
{% endblock contenent %}

templates/Empleado/lista_editar.html
{% extends 'base.html' %}

{% block title %}
    Buscar Empleados
{% endblock title %}
    

{% block contenent %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell large-12">Lista de empleados</h1>
            <div class="cell">
                <table>
                    <thead>
                    <tr>
                        <th width="200">Nombre</th>
                        <th width="150">Apellido</th>
                        <th width="150">Departamento</th>
                        <th width="150">Editar</th>
                        <th width="150">Eliminar</th>

                    </tr>
                    </thead>
                    <tbody>
                        {% for empleado in empleados %}
                        <tr>
                            <td>{{ empleado.first_name }}</td>
                            <td>{{ empleado.last_name }}</td>
                            <td>{{ empleado.departamento_id }}</td>
                            <td> 
                                <a class="button succes" href="{% url 'empleado_app:modificar_empleado' empleado.id %}">Editar</a>
                            </td>
                            <td>
                                <a class="button alert" href="{% url 'empleado_app:eliminar_empleado' empleado.id %}">Eliminar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>     
            </div>
            
            <!-- Si en nuestras vistas
            no enviamos el parametro context_object_name
            usaremos object_list  -->
        
            <div class="cell">
                 {% if is_paginated %}      
                   <nav aria-label="Pagination">
                        <ul class="pagination">
                           {% if page_obj.has_previous %}
                                <li class="pagination-previous">
                                    <a href="?page={{page_obj.previous_page_number}}">Anterior</a>  
                                </li>
                            {% endif %}
                            {% for pagina in paginator.page_range %}
                                
                                {% ifequal pagina  page_obj.number  %} 
                                    <li class="current">
                                        <span class="show-for-sr">You're on page</span> {{pagina}}
                                    </li>
                                {% else %}
                                    <li><a href="?page={{pagina}}" >{{pagina}}</a></li>             
                                {% endifequal %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                            </li>
                            {% endif %}
                        </ul>
                    </nav>
                             
                {% endif %}
            </div>
        </div>
    </div>
{% endblock contenent %}

templates/Empleado/success.html
<h1>Empleado agregado</h1>

templates/Empleado/update.html
{% extends 'base.html' %}


    {% block title %}
        Editar Empleado
    {% endblock title %}
    
    {% block contenent %} 
        <div class="grid-container">
            <div class="grid-x">
                <h1 class="cell">Actualizar datos del empleado</h1>
                <div class="cell">
                    <form class="grid-x grid-margin-x" action="" method="post">{% csrf_token %}
                        <div class="cell large-6 medium-6 small-12">
                            <label>Nombre
                                {{form.first_name}}
                            </label>
                        </div>
                        <div class="cell large-6 medium-6 small-12">
                            <label>Apellido
                                {{form.last_name}}
                            </label>
                        </div>
                        <div class="cell large-6 medium-6 small-12">
                            <label>Trabajo
                                {{form.job}}
                            </label>
                        </div>
                        <div class="cell large-6 medium-6 small-12">
                            <label>Departamento
                                {{form.departamento_id}}
                            </label>
                        </div>
                        <div class="cell large-6 medium-6 small-12">
                            <label>Habilidades
                                {{form.habilidades}}
                            </label>
                        </div>
                        <div class="cell">
                            <button  class="button succes" type="submit">Actualizar</button>
                        </div>
                                                              
                    </form>
                </div>
            </div>
        </div>
    {% endblock contenent %}